# Basic
max_width = 120
struct_lit_width = 60
struct_variant_width = 60
fn_call_width = 80
chain_width = 80
# Imports
group_imports = "StdExternalCrate"
imports_granularity = "Module"
reorder_imports = true
# Comments
comment_width = 100
normalize_comments = true
wrap_comments = true
# Consistency
newline_style = "Unix"
