[toolchain]
channel = "1.86.0" # or "stable", "nightly", etc.
components = ["cargo", "clippy", "rust-analyzer", "rustfmt"] # Optional: specify additional components
targets = [
    "x86_64-apple-darwin",      # Intel Mac
    "aarch64-apple-darwin",     # Apple Silicon Mac (if applicable)
    "x86_64-unknown-linux-gnu"  # Production (Intel Linux)
]
