use leptos::prelude::*;
use leptos_meta::{provide_meta_context, MetaTags, Stylesheet, Title};
use leptos_router::components::{Route, Router, Routes, A};
use leptos_router::hooks::use_location;
use leptos_router::StaticSegment;
use mosaic_tiles::ThemeProvider;

// Generated by macro
use crate::{
    AccordionRoute, BadgeRoute, BreadcrumbRoute, ButtonGroupRoute, ButtonRoute, CardRoute, IconRoute, LinkRoute,
    PopoverRoute, TabsRoute,
};

pub fn shell(options: LeptosOptions) -> impl IntoView {
    view! {
        <!DOCTYPE html>
        <html lang="en">
            <head>
                <meta charset="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <AutoReload options=options.clone() />
                <HydrationScripts options islands=true />
                <MetaTags />
                // Prism.js for syntax highlighting
                <link
                    rel="stylesheet"
                    href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/themes/prism-coy.min.css"
                />
                <script
                    src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/prism.min.js"
                    data-manual
                ></script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/prism-rust.min.js"></script>
            </head>
            <body>
                <App />
                // Trigger Prism.js after Leptos hydration
                <script>
                    {r#"
                    window.addEventListener('load', function() {
                    setTimeout(function() {
                    if (window.Prism) {
                        Prism.highlightAll();
                    }
                    }, 100);
                    });
                    // Also trigger on route changes and close all details elements
                    let lastPath = window.location.pathname;
                    setInterval(function() {
                    if (window.location.pathname !== lastPath) {
                    lastPath = window.location.pathname;
                    // Close all open details elements
                    document.querySelectorAll('details[open]').forEach(function(details) {
                        details.removeAttribute('open');
                    });
                    setTimeout(function() {
                        if (window.Prism) {
                            Prism.highlightAll();
                        }
                    }, 100);
                    }
                    }, 500);
                    "#}
                </script>
            </body>
        </html>
    }
}

#[component]
pub fn App() -> impl IntoView {
    // Provides context that manages stylesheets, titles, meta tags, etc.
    provide_meta_context();

    view! {
        // injects a stylesheet into the document <head>
        // id=leptos means cargo-leptos will hot-reload this stylesheet
        <Stylesheet id="leptos" href="/pkg/mosaic-demo.css" />

        // sets the document title
        <Title text="Welcome to the Mosaic component library demo" />

        // content for this welcome page
        <ThemeProvider>
            <Router>
                <AppContent />
            </Router>
        </ThemeProvider>
    }
}

#[component]
fn AppContent() -> impl IntoView {
    // Get current location for active link highlighting (must be inside Router)
    let location = use_location();
    let is_active = move |path: &str| location.pathname.get() == path;

    view! {
        <div class="min-h-screen bg-gray-50 flex flex-col">
            // Top bar with logo
            <div class="bg-white border-b border-gray-200 sticky top-0 z-40">
                <div class="flex items-center h-16 px-4 sm:px-6 lg:px-8">
                    <A href="/" attr:class="flex items-center hover:opacity-80 transition-opacity">
                        <img src="/mosaic_logo_sm.svg" alt="Mosaic Logo" class="h-6 w-6 mr-3" />
                        <h1 class="text-xl font-semibold text-gray-900">"Mosaic Tiles Demo"</h1>
                    </A>
                </div>
            </div>

            // Flex container for sidebar and content
            <div class="flex flex-1 overflow-hidden">
                // Sidebar navigation
                <aside class="w-64 bg-white border-r border-gray-200 overflow-y-auto">
                    <nav class="p-4">
                        <div class="mb-4">
                            <A
                                href="/"
                                attr:class=move || {
                                    if is_active("/") {
                                        "block px-3 py-2 rounded-md bg-gray-100 text-gray-900"
                                    } else {
                                        "block px-3 py-2 rounded-md text-gray-700 hover:bg-gray-100 hover:text-gray-900"
                                    }
                                }
                            >
                                "Home"
                            </A>
                        </div>
                        <div class="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2 px-3">
                            "Components"
                        </div>
                        <A
                            href="/accordion"
                            attr:class=move || {
                                if is_active("/accordion") {
                                    "block px-3 py-2 rounded-md bg-gray-100 text-gray-900"
                                } else {
                                    "block px-3 py-2 rounded-md text-gray-700 hover:bg-gray-100 hover:text-gray-900"
                                }
                            }
                        >
                            "Accordion"
                        </A>
                        <A
                            href="/badge"
                            attr:class=move || {
                                if is_active("/badge") {
                                    "block px-3 py-2 rounded-md bg-gray-100 text-gray-900"
                                } else {
                                    "block px-3 py-2 rounded-md text-gray-700 hover:bg-gray-100 hover:text-gray-900"
                                }
                            }
                        >
                            "Badge"
                        </A>
                        <A
                            href="/breadcrumb"
                            attr:class=move || {
                                if is_active("/breadcrumb") {
                                    "block px-3 py-2 rounded-md bg-gray-100 text-gray-900"
                                } else {
                                    "block px-3 py-2 rounded-md text-gray-700 hover:bg-gray-100 hover:text-gray-900"
                                }
                            }
                        >
                            "Breadcrumb"
                        </A>
                        <A
                            href="/button"
                            attr:class=move || {
                                if is_active("/button") {
                                    "block px-3 py-2 rounded-md bg-gray-100 text-gray-900"
                                } else {
                                    "block px-3 py-2 rounded-md text-gray-700 hover:bg-gray-100 hover:text-gray-900"
                                }
                            }
                        >
                            "Button"
                        </A>
                        <A
                            href="/button-group"
                            attr:class=move || {
                                if is_active("/button-group") {
                                    "block px-3 py-2 rounded-md bg-gray-100 text-gray-900"
                                } else {
                                    "block px-3 py-2 rounded-md text-gray-700 hover:bg-gray-100 hover:text-gray-900"
                                }
                            }
                        >
                            "Button Group"
                        </A>
                        <A
                            href="/card"
                            attr:class=move || {
                                if is_active("/card") {
                                    "block px-3 py-2 rounded-md bg-gray-100 text-gray-900"
                                } else {
                                    "block px-3 py-2 rounded-md text-gray-700 hover:bg-gray-100 hover:text-gray-900"
                                }
                            }
                        >
                            "Card"
                        </A>
                        <A
                            href="/icon"
                            attr:class=move || {
                                if is_active("/icon") {
                                    "block px-3 py-2 rounded-md bg-gray-100 text-gray-900"
                                } else {
                                    "block px-3 py-2 rounded-md text-gray-700 hover:bg-gray-100 hover:text-gray-900"
                                }
                            }
                        >
                            "Icon"
                        </A>
                        <A
                            href="/link"
                            attr:class=move || {
                                if is_active("/link") {
                                    "block px-3 py-2 rounded-md bg-gray-100 text-gray-900"
                                } else {
                                    "block px-3 py-2 rounded-md text-gray-700 hover:bg-gray-100 hover:text-gray-900"
                                }
                            }
                        >
                            "Link"
                        </A>
                        <A
                            href="/popover"
                            attr:class=move || {
                                if is_active("/popover") {
                                    "block px-3 py-2 rounded-md bg-gray-100 text-gray-900"
                                } else {
                                    "block px-3 py-2 rounded-md text-gray-700 hover:bg-gray-100 hover:text-gray-900"
                                }
                            }
                        >
                            "Popover"
                        </A>
                        <A
                            href="/tabs"
                            attr:class=move || {
                                if is_active("/tabs") {
                                    "block px-3 py-2 rounded-md bg-gray-100 text-gray-900"
                                } else {
                                    "block px-3 py-2 rounded-md text-gray-700 hover:bg-gray-100 hover:text-gray-900"
                                }
                            }
                        >
                            "Tabs"
                        </A>
                    </nav>
                </aside>

                // Main content area
                <main class="flex-1 overflow-y-auto">
                    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
                        <Routes fallback=|| "Page not found.".into_view()>
                            <Route path=StaticSegment("") view=HomePage />
                            <Route path=StaticSegment("accordion") view=AccordionRoute />
                            <Route path=StaticSegment("badge") view=BadgeRoute />
                            <Route path=StaticSegment("breadcrumb") view=BreadcrumbRoute />
                            <Route path=StaticSegment("button") view=ButtonRoute />
                            <Route path=StaticSegment("button-group") view=ButtonGroupRoute />
                            <Route path=StaticSegment("card") view=CardRoute />
                            <Route path=StaticSegment("icon") view=IconRoute />
                            <Route path=StaticSegment("link") view=LinkRoute />
                            <Route path=StaticSegment("popover") view=PopoverRoute />
                            <Route path=StaticSegment("tabs") view=TabsRoute />
                        </Routes>
                    </div>
                </main>
            </div>
        </div>
    }
}

/// Renders the home page of your application.
#[component]
fn HomePage() -> impl IntoView {
    view! {
        <div class="max-w-4xl mx-auto px-4 py-12">
            <div class="flex justify-center mb-3">
                <img src="/mosaic_logo.svg" alt="Mosaic Logo" class="h-[576px] w-[576px]" />
            </div>

            <p class="text-lg text-gray-700 mb-8">
                "A Leptos component library built with Tailwind CSS v4, designed to work exclusively with Leptos islands architecture. Components use feature flags for selective inclusion and compile styles at build time."
            </p>

            <div class="space-y-8">
                <section>
                    <h2 class="text-2xl font-semibold mb-4">"Architecture"</h2>
                    <ul class="space-y-2 text-gray-700">
                        <li>
                            "• Built on Leptos 0.8 for server-side rendering and reactive web applications"
                        </li>
                        <li>"• Styled with Tailwind CSS v4 utility classes"</li>
                        <li>"• Feature flags enable opt-in component inclusion"</li>
                        <li>"• CSS bundling happens at build time via build.rs"</li>
                        <li>
                            "• ThemeProvider component injects bundled styles (always available, not a feature flag)"
                        </li>
                    </ul>
                </section>

                <section>
                    <h2 class="text-2xl font-semibold mb-4">"Component Structure"</h2>
                    <p class="text-gray-700 mb-3">
                        "Each component consists of a Rust module and dedicated CSS file:"
                    </p>
                    <pre class="bg-gray-100 p-4 rounded-lg text-sm overflow-x-auto">
                        <code>
                            {"src/components/[component_name]/\n"}
                            {"├── mod.rs              # Component implementation\n"}
                            {"└── [component_name].css # Tailwind CSS styles"}
                        </code>
                    </pre>
                </section>

                <section>
                    <h2 class="text-2xl font-semibold mb-4">"Usage"</h2>
                    <p class="text-gray-700 mb-3">
                        "Components are enabled via Cargo features. Wrap your Router with ThemeProvider to load styles:"
                    </p>
                    <pre>
                        <code class="language-rust">
                            {"use leptos::prelude::*;\n"}
                            {"use leptos_router::components::{Router, Routes, Route};\n"}
                            {"use mosaic_tiles::{ThemeProvider, Button};\n\n"} {"#[component]\n"}
                            {"pub fn App() -> impl IntoView {\n"} {"    view! {\n"}
                            {"        <ThemeProvider>\n"} {"            <Router>\n"}
                            {"                <main>\n"}
                            {"                    <Routes fallback=|| \"Not found\".into_view()>\n"}
                            {"                        <Route path=StaticSegment(\"\") view=HomePage />\n"}
                            {"                    </Routes>\n"} {"                </main>\n"}
                            {"            </Router>\n"} {"        </ThemeProvider>\n"} {"    }\n"}
                            {"}"}
                        </code>
                    </pre>
                </section>

                <section>
                    <h2 class="text-2xl font-semibold mb-4">"Available Components"</h2>
                    <p class="text-gray-700 mb-3">
                        "Use the navigation above to explore component examples and API documentation."
                    </p>
                </section>
            </div>
        </div>
    }
}
