# Run all fmt and clippy checks
check:
    just --check --fmt --unstable
    cargo +nightly fmt -p mosaic-tiles -p demo_macro --check
    leptosfmt --check leptos-dpe
    leptosfmt --check mosaic/demo
    cargo clippy -- -D warnings

# Format all rust code (cargo fmt for non-leptos crates, leptosfmt for leptos crates)
fmt:
    cargo +nightly fmt -p mosaic-tiles -p demo_macro
    leptosfmt leptos-dpe
    leptosfmt mosaic/demo

# Fix justfile formatting. Warning: will change existing file. Please first use check.
fix:
    just --fmt --unstable

# Run all rust builds
build:
    cargo build --all-targets

# Run server
run:
    cargo run --bin server --release

# Run all tests
test:
    cargo test --tests

# Clean all build artifacts
clean:
    cargo clean

# Watch for changes and run tests
watch:
    cargo watch -x test

###################
# Mosaic targets
###################

# Start the mosaic demo and watch mosaic tiles
[group('mosaic')]
watch-mosaic-demo:
    #!/usr/bin/env sh
    cd mosaic/demo
    cargo leptos watch -- --watch ../tiles

# Build Docker image for mosaic demo
[group('mosaic')]
build-docker-mosaic-demo:
    docker build -f mosaic/demo/Dockerfile -t mosaic-demo ..

# Run mosaic demo Docker container on port 8080
[group('mosaic')]
run-docker-mosaic-demo:
    docker run --rm -p 8080:8080 mosaic-demo

###################
# Leptos DPE targets
###################

# Start the leptos-dpe with hot reload
[group('leptos-dpe')]
watch-leptos-dpe:
    cargo leptos watch --project=leptos-dpe -- --watch ../mosaic/tiles
