services:
  playwright:
    build:
      context: ../../..
      dockerfile: modules/design_system/playground/Dockerfile
    volumes:
      - ./tests:/app/modules/design_system/playground/tests
      - ./playwright-report:/app/modules/design_system/playground/playwright-report
      - ./output:/app/modules/design_system/playground/output
    environment:
      - CI=true
    working_dir: /app/modules/design_system/playground
    command: npm run test:update-snapshots