mod about_us;
mod contact;
mod data;
mod data2;
mod data3;
mod faq;
mod home;
mod knowledge_hub;
mod news;
mod project_data;
pub mod projects;
mod services;
mod status;

pub use about_us::about_us;
pub use contact::contact;
pub use data::data;
pub use data2::data_with_column2;
pub use data3::data_with_column3;
pub use faq::faq;
pub use home::home;
pub use knowledge_hub::knowledge_hub;
pub use news::news;
pub use projects::projects;
pub use services::services;
pub use status::status;
