@startuml Domain Entities

package toplevel {

  class Project {
    The Project.
    -- Required Fields --
    .. (1) ..
    -UUID id
    -String type
    -Date created
    -Date modified
    +Shortcode shortcode
    +String name
    +MultiLanguageText description
    +Date startDate
    +URL url

    .. (1 - n) ..
    +Dataset[] datasets
    +MultiLanguageText[] keywords
    +MultiLanguageText[] disciplineTexts
    +URL[] disciplineRefs
    +MultiLanguageText[] temporalCoverageTexts
    +URL[] temporalCoverageRefs
    +URL[] spatialCoverages
    +Person[] funderPersons
    +Organization[] funderOrganizations

    -- Optional Fields --
    .. (0 - 1) ..
    +DataManagementPlan dataManagementPlan
    +Date endDate
    +Person contactPerson
    +Organization contactOrganization
    +String howToCite
    +URL secondaryURL

    .. (0 - n) ..
    +String[] publications
    +Grant[] grants
    +MultiLanguageText[] alternativeNames
  }

  note left of Project::disciplineTexts
    `disciplineTexts` and `disciplineRefs`
    together are `disciplines` (1-n)
  end note

  note left of Project::temporalCoverageTexts
    `temporalCoverageTexts` and `temporalCoverageRefs`
    together are `temporalCoverages` (1-n)
  end note

  note left of Project::spatialCoverage
    Must be AuthorityReference
  end note

  note left of Project::funderPersons
    `funderPersons` and `funderOrganizations`
    together are `funders` (1-n)
  end note

  note left of Project::contactPerson
    `contactPerson` and `contactOrganization`
    together are `contactPoint` (0-1)
  end note

  class Dataset {
    A Dataset belonging to the project.
    -- Required Fields --
    .. (1) ..
    -UUID id
    -String type
    -Date created
    -Date modified
    +String title
    +String accessConditions
    +String howToCite
    +Status status

    .. (1 - n) ..
    +MultiLanguageText[] abstractTexts
    +URL[] abstractURLs
    +TypesOfData[] typesOfData
    +URL[] licenses
    +MultiLanguageText[] languages
    +Attribution[] attributions

    -- Optional Fields --
    .. (0 - 1) ..
    +Date datePublished
    +Date dateCreated
    +Date dateModified
    +URL distribution

    .. (0 - n) ..
    +MultiLanguageText[] alternativeTitles
    +URL[] urls
    +MultiLanguageText[] documentationTexts
    +URL[] documentationURLs
  }

  note left of Dataset::abstractTexts
    `abstractTexts` and `abstractURLs`
    together are `abstracts` (1-n)
  end note

  note left of Dataset::documentationTexts
    `documentationTexts` and `documentationURLs`
    together are `documentations` (0-n)
  end note

  class DataManagementPlan {
    .. (1) ..
    -UUID id
    -String type
    -Date created
    -Date modified

    .. (0 - 1) ..
    +boolean available
    +URL url

  }

  class Grant {
    A financial grant.
    -- Required Fields --
    .. (1) ..
    -UUID id
    -String type
    -Date created
    -Date modified

    .. (1 - n) ..
    +Person[] funderPersons
    +Organization[] funderOrganizations

    -- Optional Fields --
    .. (0 - 1) ..
    +String number
    +MultiLanguageText name
    +URL url

  }

  note left of Grant::funderPersons
    `funderPersons` and `funderOrganizations`
    together are `funders` (1-n)
  end note

  class Person {
    A Person.
    -- Required --
    .. (1) ..
    -UUID id
    -String type
    -Date created
    -Date modified

    .. (1 - n) ..
    +String[] jobTitles
    +String[] givenNames
    +String[] familyNames
    +Organization[] affiliation

    -- Optional --
    .. (0 - 1) ..
    +Address address

    .. (0 - 2) ..
    +Email[] emails

    .. (0 - n) ..
    +URL[] authorityRefs

  }

  note left of Person::authorityRefs
    Must be AuthorityReference
  end note

  class Organization {
    An Organization.
    -- Required --
    .. (1) ..
    -UUID id
    -String type
    -Date created
    -Date modified
    +String name

    -- Optional --
    .. (0 - 1) ..
    +URL url
    +Address address
    +Email email

    .. (0 - n) ..
    +MultiLanguageText[] alternativeNames
    +URL[] authorityRefs

  }

  note left of Organization::authorityRefs
    Must be AuthorityReference
  end note

  class Address {
    Struct containing a postal address.
    -- Required --
    .. (1) ..
    +String street
    +String postalCode
    +String locality
    +String country

    -- Optional --
    .. (0 - 1) ..
    +String additional

  }

  class Attribution {
    Struct holding information on how work on a dataset can be attributed to a person.
    -- Required Fields --
    .. (1) ..
    +Person person
    .. (1 - n) ..
    +String[] roles

  }
  

}

package valueobject {

  class Shortcode{
    Valueobject struct holding a shortcode.
    -- Fields --
    +String value
    -- Methods --
    .. Static Methods ..
    {static} +URL newShortcode()
    {static} +URL zeroShortcode()
    .. Object Methods ..
    +String string()
    +boolean equals()
  }

  class Email{
    Valueobject struct holding an e-mail address.
    -- Fields --
    +String value
    -- Methods --
    .. Static Methods ..
    {static} +URL newEmail()
    {static} +URL zeroEmail()
    .. Object Methods ..
    +String string()
    +boolean equals()
  }

  class URL{
    Valueobject struct holding an e-mail address.
    -- Fields --
    +URLType type
    +String url
    +String propertyID
    -- Methods --
    .. Static Methods ..
    {static} +URL newURL()
    {static} +URL zeroURL()
    .. Object Methods ..
    +String string()
    +boolean equals()
  }

  class Date {
    Valueobject struct holding an ISO date.
    -- Fields --
    +String value
    'TODO: string or date String
    -- Methods --
    .. Static Methods ..
    {static} +URL newDate()
    {static} +URL zeroDate()
    .. Object Methods ..
    +String string()
    +boolean equals()
  }

  class MultiLanguageText {
    Valueobject struct holding text in multiple different languages.
    -- Fields --
    +Map[ISOLanguage,String] value
    -- Methods --
    .. Static Methods ..
    {static} +URL newMultiLanguageText()
    {static} +URL zeroMultiLanguageText()
    .. Object Methods ..
    +String string()
    +boolean equals()
  }

  class ISOLanguage {
    Valueobject struct holding a two character ISO language tag.
    -- Fields --
    +String value
    -- Methods --
    .. Static Methods ..
    {static} +URL newISOLanguage()
    {static} +URL zeroISOLanguage()
    .. Object Methods ..
    +String string()
    +boolean equals()
  }
}

package enums {

  enum TypesOfData {
    XML
    Text
    Image
    Video
    Audio
  }

  enum Status {
    In_planning
    Ongoing
    On_hold
    Finished
  }

  enum URLType {
    Enum holding different types of URLs:
    Default is `URL`, however, if a URL points to an authority file supported by DSP,
    there will be a special for it here.
    ---
    URL
    Geonames
    Pleiades
    Skos
    Periodo
    Chronontology
    GND
    VIAF
    Grid
  }

}

package externals {
  class uuid::UUID {
    Unique ID
  }
}


Project --> Dataset
Project --> DataManagementPlan
Project --> Grant
Dataset --> Attribution
Attribution --> Person
Person --> Organization
Person --> Address
Organization --> Address


@enduml
